/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NflPromptsRouteImport } from './routes/nfl-prompts'
import { Route as NbaPromptsRouteImport } from './routes/nba-prompts'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'

const NflPromptsRoute = NflPromptsRouteImport.update({
  id: '/nfl-prompts',
  path: '/nfl-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const NbaPromptsRoute = NbaPromptsRouteImport.update({
  id: '/nba-prompts',
  path: '/nba-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/nba-prompts': typeof NbaPromptsRoute
  '/nfl-prompts': typeof NflPromptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/nba-prompts': typeof NbaPromptsRoute
  '/nfl-prompts': typeof NflPromptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/nba-prompts': typeof NbaPromptsRoute
  '/nfl-prompts': typeof NflPromptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculator' | '/nba-prompts' | '/nfl-prompts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculator' | '/nba-prompts' | '/nfl-prompts'
  id: '__root__' | '/' | '/calculator' | '/nba-prompts' | '/nfl-prompts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  NbaPromptsRoute: typeof NbaPromptsRoute
  NflPromptsRoute: typeof NflPromptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nfl-prompts': {
      id: '/nfl-prompts'
      path: '/nfl-prompts'
      fullPath: '/nfl-prompts'
      preLoaderRoute: typeof NflPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nba-prompts': {
      id: '/nba-prompts'
      path: '/nba-prompts'
      fullPath: '/nba-prompts'
      preLoaderRoute: typeof NbaPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  NbaPromptsRoute: NbaPromptsRoute,
  NflPromptsRoute: NflPromptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
